# Generated by Django 3.2.6 on 2022-02-02 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=254, verbose_name='Batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom de la doc technique')),
                ('manuel', models.FileField(max_length=254, upload_to='manuel/', verbose_name='Télécharger le manuel')),
                ('version', models.CharField(default='x.x.x', max_length=50, verbose_name='Version de la doc technique')),
            ],
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=254, verbose_name='Etage')),
                ('batiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pompe.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Fabriquant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, max_length=254, null=True, upload_to='logo_fabriquant/')),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('ville', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Huile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to='huile_img/', verbose_name='Image')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom de la pompe')),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Quantité en stock')),
                ('ref_fab', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Référence')),
                ('date_maj', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de mise à jour du stock')),
                ('information', models.TextField(blank=True, max_length=200, null=True, verbose_name='Information(s) complémentaire')),
                ('fabriquant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.fabriquant')),
            ],
        ),
        migrations.CreateModel(
            name='ModelePompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to='pompe_img/')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom de la pompe')),
                ('modele', models.CharField(default='', max_length=50, verbose_name='Modèle de la pompe')),
                ('phasage', models.CharField(choices=[('Monophasé', 'Monophasé'), ('Triphasé', 'Triphasé')], default='Monophasé', max_length=15, verbose_name='Phasage du moteur électrique')),
                ('puissance', models.CharField(choices=[('50 Hertz', '50 Hertz'), ('60 Hertz', '60 Hertz')], default='50', max_length=20, verbose_name='Puissance du moteur')),
                ('technologie', models.CharField(choices=[('Sèches - Membranes', 'Sèches - Membranes'), ('Sèches - Vis', 'Sèches - Vis'), ('Palettes - 1 étage', 'Palettes - 1 étage'), ('Palettes - 2 étages', 'Palettes - 2 étages')], max_length=30, verbose_name='Technologie du vide')),
                ('vide_theo', models.FloatField(default=0, verbose_name='Vide limite Fabriquant')),
                ('documentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.doc')),
                ('fabriquant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.fabriquant')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255, verbose_name="Nom complet de l'équipe")),
                ('sigle', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Abbreviation du nom')),
                ('nom_responsable', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name="Responsable de l'équipe")),
                ('email_responsable', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Email du Responsable')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date de création')),
                ('lieux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.etage')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=254, verbose_name='Piece')),
                ('etage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pompe.etage')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=254, verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='VersionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='x.x.x', max_length=10, verbose_name='Version')),
                ('maj_maj', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Mise à jour majeur')),
                ('maj_min', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Mise à jour mineur')),
                ('bug', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Bugs')),
                ('texte', models.TextField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('date_version', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='StockPompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise_en_service', models.DateField(auto_now=True)),
                ('vidange', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de la prochaine vidange')),
                ('place', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Emplacement dans la pièce')),
                ('vide_user', models.FloatField(blank=True, default=0, verbose_name='Vide limite testé')),
                ('num_serie', models.CharField(default='', max_length=150, verbose_name='Numéro de série')),
                ('num_inventaire', models.CharField(default='', max_length=150, verbose_name="Numéro d'inventaire")),
                ('statut', models.CharField(choices=[('A', 'Active'), ('S', 'En Stock'), ('R', 'En réparation'), ('P', 'En panne')], default='', max_length=1, verbose_name='Etat actuel de la pompe')),
                ('historique', models.TextField(blank=True, max_length=500, null=True, verbose_name='historique de la pompe')),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.modelequipe')),
                ('huile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.huile')),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.piece')),
                ('pompe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.modelepompe')),
            ],
        ),
        migrations.CreateModel(
            name='PiecesPompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom de la pièce détachée')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to='piecepompe_img/')),
                ('date_maj', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de mise à jour du stock')),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Quantité en stock')),
                ('information', models.TextField(blank=True, max_length=200, null=True, verbose_name='Information(s) complémentaire(s)')),
                ('fabriquant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.fabriquant')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.piece')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom du kit')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to='kit_img/')),
                ('date_maj', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de mise à jour du stock')),
                ('ref_fab', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Référence Fabriquant')),
                ('nom_revendeur', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Revendeur')),
                ('ref_rev', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Référence Revendeur')),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Quantité en stock')),
                ('information', models.TextField(blank=True, max_length=200, null=True, verbose_name='Information(s) complémentaire')),
                ('fabriquant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.fabriquant')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.piece')),
            ],
        ),
        migrations.AddField(
            model_name='huile',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompe.piece'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pompe.site'),
        ),
    ]
