# Generated by Django 3.2.6 on 2021-08-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompe',
            name='nombre_etage',
            field=models.FloatField(default=0),
        ),
    ]
