# Generated by Django 3.2.6 on 2021-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0004_auto_20210826_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pompes',
            name='kit_maintenance',
        ),
    ]
