# Generated by Django 3.2.6 on 2021-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0005_remove_pompes_kit_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompes',
            name='manuel',
            field=models.FileField(default='', max_length=254, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='piecespompe',
            name='image',
            field=models.ImageField(max_length=254, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='image',
            field=models.ImageField(max_length=254, upload_to='media/'),
        ),
    ]
