# Generated by Django 3.2.6 on 2021-08-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0006_auto_20210826_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='huile',
            name='image',
            field=models.ImageField(default='', max_length=254, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='huile',
            name='information',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='huile',
            name='localisation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='huile',
            name='marque',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='huile',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='huile',
            name='quantite',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='huile',
            name='type_pompe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kit',
            name='image',
            field=models.ImageField(default='', max_length=254, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='kit',
            name='information',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='kit',
            name='localisation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kit',
            name='marque',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kit',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kit',
            name='quantite',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kit',
            name='reference',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kit',
            name='type_pompe',
            field=models.CharField(default='', max_length=100),
        ),
    ]
