# Generated by Django 3.2.6 on 2021-08-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0007_auto_20210826_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='type_pompe',
        ),
    ]
