# Generated by Django 3.2.6 on 2021-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0008_remove_kit_type_pompe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='image',
            field=models.ImageField(max_length=254, upload_to='pompe/static/'),
        ),
    ]
