# Generated by Django 3.2.6 on 2021-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0009_alter_pompes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='image',
            field=models.ImageField(max_length=254, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='manuel',
            field=models.FileField(default='', max_length=254, upload_to='media/upload/'),
        ),
    ]
