# Generated by Django 3.2.6 on 2021-09-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0010_auto_20210908_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='reference',
            new_name='reference_marque',
        ),
        migrations.AddField(
            model_name='kit',
            name='reference_revendeur',
            field=models.CharField(default='', max_length=50),
        ),
    ]
