# Generated by Django 3.2.6 on 2021-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0012_kit_nom_revendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecespompe',
            name='information',
            field=models.CharField(default='', max_length=50),
        ),
    ]
