# Generated by Django 3.2.6 on 2021-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0013_piecespompe_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompes',
            name='phasage',
            field=models.CharField(choices=[('M', 'Monophasé'), ('T', 'Triphasé')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='pompes',
            name='vide_teste',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pompes',
            name='vide_theorique',
            field=models.FloatField(default=0),
        ),
    ]
