# Generated by Django 3.2.6 on 2021-09-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0015_pompes_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huile',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='kit',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='piecespompe',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
