# Generated by Django 3.2.6 on 2021-09-09 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0017_auto_20210909_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huile',
            name='information',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kit',
            name='information',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='date_derniere_vidange',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='information',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='mise_en_service',
            field=models.DateField(auto_now_add=True),
        ),
    ]
