# Generated by Django 3.2.6 on 2021-09-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0018_auto_20210909_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='phasage',
            field=models.CharField(choices=[('Mono', 'Monophasé'), ('Tri', 'Triphasé')], default='M', max_length=4),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='statut',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Stockage'), ('R', 'En Réparation'), ('EP', 'En panne')], default='A', max_length=2),
        ),
    ]
