# Generated by Django 3.2.6 on 2021-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0019_auto_20210909_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='image',
            field=models.ImageField(max_length=254, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='manuel',
            field=models.FileField(blank=True, default='', max_length=254, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='pompes',
            name='statut',
            field=models.CharField(choices=[('A', 'Actif'), ('S', 'Stockage'), ('R', 'En Réparation'), ('EP', 'En panne')], default='A', max_length=2),
        ),
    ]
