# Generated by Django 3.2.6 on 2021-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0020_auto_20210913_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='image',
            field=models.ImageField(blank=True, max_length=254, upload_to=''),
        ),
    ]
