# Generated by Django 3.2.6 on 2021-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0021_alter_pompes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huile',
            name='image',
            field=models.ImageField(default='', max_length=254, upload_to=''),
        ),
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(default='', max_length=254, upload_to=''),
        ),
        migrations.AlterField(
            model_name='piecespompe',
            name='image',
            field=models.ImageField(max_length=254, upload_to=''),
        ),
    ]
