# Generated by Django 3.2.6 on 2021-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0022_auto_20210913_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecespompe',
            name='image',
            field=models.ImageField(default='', max_length=254, upload_to=''),
        ),
    ]
