# Generated by Django 3.2.6 on 2021-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0023_alter_piecespompe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='nombre_etage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
