# Generated by Django 3.2.6 on 2021-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0024_alter_pompes_nombre_etage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='statut',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Stockage'), ('R', 'En Réparation'), ('P', 'En panne')], default='A', max_length=1),
        ),
    ]
