# Generated by Django 3.2.6 on 2021-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0025_alter_pompes_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pompes',
            old_name='type',
            new_name='modele',
        ),
        migrations.AlterField(
            model_name='pompes',
            name='mise_en_service',
            field=models.DateField(auto_now=True),
        ),
    ]
