# Generated by Django 3.2.6 on 2021-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0026_auto_20210916_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompes',
            name='puissance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
